### ISSUE TITLE
Blizzard sight configurable list?

### ISSUE THREAD

**Issue by Slendykins** [LegoMaster3650/LC-FairGiants#1]
Hey i've had great use out of this mod!

Finally feels like Giants aren't as much of a pain anymore but i'd like to ask if there could be a snowy moon selection list, a bit what the custom dungeon/interior devs have added to their configs.

I'm saying this as I believe the snowy moon eyesight is being applied to custom moons like Auralis (Starlancer moons), that's a snowy moons but it's crystal clear and it's quite easy to get past giants there because they can barely see you.

**Comment by LegoMaster3650** [comment]
Ah, probably should've seen that coming. (My method for detection was checking the snowy footsteps variable 💀)
Will fix, should be out within a few days.

**Comment by LegoMaster3650** [comment]
Added in 9057e9a sorry for being a bit late (also updated to v50 sorry if u dont like that)
