### ISSUE TITLE
Doubles the spawn rate of Dogs and Giants

### ISSUE THREAD

**Issue by Lunxara** [LegoMaster3650/LC-FairGiants#2]
Hello I've noticed this mod seems to make double the amount of Dogs and Forest Giants spawn, and it becomes really frustrating tbh. I hope you can look into fixing this because obviously this shouldn't be happening :(

**Comment by LegoMaster3650** [comment]
That is indeed strange and shouldn't be happening... The mod doesn't touch ANY spawning code, so I'm unsure how it could even be causing this. How did you determine my mod is responsible?

**Comment by Lunxara** [comment]
> That is indeed strange and shouldn't be happening... The mod doesn't touch ANY spawning code, so I'm unsure how it could even be causing this. How did you determine my mod is responsible?

Okay so luckily it isn't your mod, I sadly assumed that it was because this issue started for me right after adding FairGiants and I will say that I have noticed Giants tend to wander closer together more often still compared to Vanilla so it still seems like Giant spawns are increased but they're not. I found out it was MEOFork doubling spawn rates after adding your mod paired with a bunch of other custom enemy mods, it just started causing chaos right after adding your mod sadly 😭 I finally saw in the logs that it was MEOF messing with power levels and after removing it the problem stopped ^^ so I think this issue is safe to close now 😅
